---
title: "Data cleaning for the house pricing estimation"
output: R notebook
---

```{r}
train<-read.csv("train.csv",header=TRUE)
head(train)
clean=train
```

```{r}
train_na=colSums(sapply(train,is.na))
train_na=train_na[train_na>0]
train_na
```
```{r}
#Generic functions for imputation
data_impute=function(column='column',value='value')
  train[is.na(train[column]),column]=value
```

```{r}
#Imputation for lot frontage
LotFrontage_wna=which(!is.na(train['LotFrontage']))
cor(train$LotFrontage[LotFrontage_wna],train$LotArea[LotFrontage_wna])
cor(train$LotFrontage[LotFrontage_wna],sqrt(train$LotArea[LotFrontage_wna]))
#The observed correlation for LotFrontage vs the sqrt of LotArea is high, so we are using the sqrt of LotArea values to impute
LotFrontage_na=which(is.na(train['LotFrontage']))
sqrtLotArea=sqrt(train$LotArea[LotFrontage_na])
clean$LotFrontage[LotFrontage_na]=sqrtLotArea
min(clean$LotFrontage)
max(clean$LotFrontage)
```
```{r}
#Imputation for Alley
clean$Alley<-as.character(clean$Alley)
clean$Alley[is.na(clean$Alley)]<-'NoAccess'
```

```{r}
#Imputation for MasVnrType
cmp=which(is.na(train['MasVnrType']))==which(is.na(train['MasVnrArea']))
which(cmp==FALSE)
#The NAs are same for both the columns, so we tke that the mason veneer isn't present in the house
clean$MasVnrType<-as.character(clean$MasVnrType)
clean$MasVnrType[is.na(clean$MasVnrType)]<-'None'
clean$MasVnrArea[is.na(clean$MasVnrArea)]<-0
```
```{r}
#Imputation for the basement paramteres
#NA here implies that there is no basement, so we can simply assign 'None'
clean$BsmtQual<-as.character(clean$BsmtQual)
clean$BsmtQual[is.na(clean$BsmtQual)]<-'None'
clean$BsmtCond<-as.character(clean$BsmtCond)
clean$BsmtCond[is.na(clean$BsmtCond)]<-'None'
clean$BsmtExposure<-as.character(clean$BsmtExposure)
clean$BsmtExposure[is.na(clean$BsmtExposure)]<-'None'
clean$BsmtFinType1<-as.character(clean$BsmtFinType1)
clean$BsmtFinType1[is.na(clean$BsmtFinType1)]<-'None'
clean$BsmtFinType2<-as.character(clean$BsmtFinType2)
clean$BsmtFinType2[is.na(clean$BsmtFinType2)]<-'None'
```
```{r}
#Imputation for Electrical
summary(train$Electrical)
#Since only one value is missing, we can assign the most occured value to it
clean$Electrical<-as.character(clean$Electrical)
clean$Electrical[is.na(clean$Electrical)]<-'SBrkr'
```
```{r}
#writing the cleaned data into a csv file "clean.csv"
write.csv(clean, file="clean.csv")
```





