---
title: "R Notebook"
output: html_notebook
author: "Ileena Mitra"
date: "March 20th, 2017"
---

#Math 289c Final Project

Set up
```{r echo=FALSE, warning=FALSE}
library(readr)

clean <- read_csv("~/Google_Drive/UCSD/Winter2017/ExpDataAnalysis/Projects/Final/kaggle_predict_house_prices/cleaned_data/clean.csv")
rownames(clean) <- clean$Id
clean$Id <- NULL
clean$X1 <- NULL
cleandmy <- read_csv("~/Google_Drive/UCSD/Winter2017/ExpDataAnalysis/Projects/Final/kaggle_predict_house_prices/cleaned_data/cleandmy.csv")
cleandmy$X <- NULL
cleandmy$X1 <- NULL


# ensure the results are repeatable
set.seed(888)
```


Spit the data into numerical versus categoral data
```{r}
clean.num <- clean[ , sapply(clean, is.numeric)]
clean.char <- clean[ , sapply(clean, is.character)]

```

##Feature Correlation
http://machinelearningmastery.com/feature-selection-with-the-caret-r-package/
```{r}
# load the library
library(mlbench)
library(caret)
dat<- clean.num[,names(clean.num) != "SalePrice"]

# calculate correlation matrix
correlationMatrix <- cor(dat)
# summarize the correlation matrix
###print(correlationMatrix)

# find attributes that are highly corrected (ideally >0.75)
highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=0.75, names = TRUE)
# print indexes of highly correlated attributes
print(highlyCorrelated)

View(correlationMatrix[,highlyCorrelated])
```





##Feature Selection
```{r}
dat<- clean.num

# define the control using a random forest selection function
control <- rfeControl(functions=rfFuncs, method="boot", number=10)
# run the RFE algorithm
results <- rfe(dat[,names(dat) != "SalePrice"], dat$SalePrice, sizes=c(1:36), rfeControl=control)
# summarize the results
print(results)
# list the chosen features
predictors(results)
# plot the results
plot(results, type=c("g", "o"))
```






######OTHER TRIAL METHODS#######
We then fit a tree on the dat frame with appropriate columns.
```{r}
library(tree)
dat <- clean.num
dat.tree <- tree(log(SalePrice) ~., data = dat)
plot(dat.tree, type="uniform")
text(dat.tree)
```




Regression method to test features
```{r}
dat<- clean.num
lr.all <- glm(log(SalePrice) ~., data = dat, family = gaussian)
#display the results
print(summary(lr.all))
```


